server-info:
  port: 8080
  implementationName: 积木brick-Yggdrasil验证端
  implementationVersion: 0.3.0
  loginRate: 1
  log-level: info

server:
  port: ${server-info.port}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    db-config:
      id-type: auto

logging:
  group:
    o: net.sengimu
  level:
    root: info
    o: ${server-info.log-level}
  file:
    name: log/server.log

database: sqlite
spring:
  profiles:
    include: ${database}
