# 请确保你清楚明白配置含义后再做修改

# 服务器信息
server-info:
  # 开放端口
  port: 80
  # 服务器名称
  serverName: 积木brick-Yggdrasil验证端
  # 登录限速
  # 单位为秒,代表x秒可登录一次
  loginRate: 5
  # 日志级别
  log-level: info

# 使用的数据库,填 sqlite 或 mysql
database: sqlite

# MySQL配置
mysql:
  host: localhost
  port: 3306
  username: root
  password: root
  # 数据库名
  database: brick